### ISSUE TITLE
Beginning of class checklist

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/code4lib_precon_demo#10]
- [ ] names on backs of laptops
- [ ] get people to submit post-its with things they want to learn
- [ ] sort people by ruby experience and have them pair (or clumps of 3?). 
- [ ] pull repositories, run `bin/setup`, run the application
- [ ] get an initial typist
- [ ] office hours

Rough timeline:
- 1:30 Beginning of class prep
- 2:00 Code4Lib branding (#1)
- 2:30 — Break —
- 2:45 Blacklight configuration (#2, #3, #5, #6)
- 3:45 — Break —
- 4:00 Pick one of #4, #8, #7, or suggestions from class
- 4:30 Decamp to office hours location
